table Sales
	lineageTag: 447cb029-ca15-42d0-b03e-f721c4bd83b7

	column So_Date
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 9b9622bb-f263-4c5d-98a6-244085fc90ae
		summarizeBy: none
		sourceColumn: So_Date

		annotation SummarizationSetBy = Automatic

	column So_Nbr
		dataType: string
		sourceProviderType: varchar(254)
		lineageTag: d57de5ef-428e-4298-8fa7-17da1add7381
		summarizeBy: none
		sourceColumn: So_Nbr

		annotation SummarizationSetBy = Automatic

	column Part_Nbr
		dataType: string
		sourceProviderType: varchar(254)
		lineageTag: b54e6292-3533-43b7-874f-f2bf6c083273
		summarizeBy: none
		sourceColumn: Part_Nbr

		annotation SummarizationSetBy = Automatic

	column Cust_Nbr
		dataType: string
		sourceProviderType: varchar(254)
		lineageTag: 34e57b71-a4de-485f-9e0d-930cf4d6aaa6
		summarizeBy: none
		sourceColumn: Cust_Nbr

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: c9f73c2f-8ef3-4173-a208-fb7021b45dc4
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	column 'Sales Amount'
		dataType: double
		sourceProviderType: float
		lineageTag: b7dd03dd-dd5f-4193-bbc4-55ad75e8221f
		summarizeBy: sum
		sourceColumn: Sales Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cost
		dataType: double
		sourceProviderType: float
		lineageTag: 918ea1c2-8b50-40a8-8fac-1d8e4adc53b1
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount
		dataType: double
		sourceProviderType: float
		lineageTag: 469430dd-be5e-449d-bdf0-a922d3f7e7a2
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		sourceProviderType: float
		lineageTag: 81093f1a-70bf-4f4d-bf93-a5c82f6882dc
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales = m
		mode: import
		source =
				let
				    Source = Sql.Databases("RHP-D-FWKKK74\SQLPBI"),
				    ReportPBI = Source{[Name="ReportPBI"]}[Data],
				    dbo_vw_SOD = ReportPBI{[Schema="dbo",Item="vw_SOD"]}[Data],
				    #"Renamed Ln_Del_Qty,Ln_del_Ext_Price" = Table.RenameColumns(dbo_vw_SOD,{{"Ln_Del_Qty", "Qty"}, {"Ln_Del_Ext_Price", "Sales Amount"}}),
				    #"Added Column Cost" = Table.AddColumn(#"Renamed Ln_Del_Qty,Ln_del_Ext_Price", "Cost", each [Last_Bk_Cost] * [Qty]),
				    #"Added Column Discount" = Table.AddColumn(#"Added Column Cost", "Discount", each [Trade_Disc_Amount] * [Qty]),
				    #"Added Profit" = Table.AddColumn(#"Added Column Discount", "Profit", each [Sales Amount] - [Cost]),
				    #"Removed Columns ID,Trade_Disc_Amount,Last_Bk_Cost" = Table.RemoveColumns(#"Added Profit",{"ID", "Trade_Disc_Amount", "Last_Bk_Cost"}),
				    #"Removed 0 on Sales Amount" = Table.SelectRows(#"Removed Columns ID,Trade_Disc_Amount,Last_Bk_Cost", each ([Sales Amount] <> 0)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed 0 on Sales Amount",{{"Cost", type number}, {"Discount", type number}, {"Profit", type number}, {"So_Date", type datetime}}),
				    #"Filtered Year" = Table.SelectRows(#"Changed Type", each [So_Date] > #datetime(2023, 1, 1, 0, 0, 0))
				in
				    #"Filtered Year"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

